name: quantos
description: Everybody can understand quantum computing - Quantos is your beginner-friendly suite for learning about and programming quantum annealers.

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=2.18.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  tuple: ^2.0.1
  http: ^0.13.5
  flutter_bloc: ^8.1.1
  rive: ^0.9.1
  qubo_embedder: ^0.1.0
  universal_platform: ^1.0.0+1
  auto_size_text: ^3.0.0
  flutter_math_fork: ^0.6.3
  flutter_switch: ^0.3.2
  curved_navigation_bar: ^1.0.3
  percent_indicator: ^4.2.2
  page_transition: ^2.0.9
  animated_text_kit: ^4.2.2
  package_info_plus: 3.0.1
  shared_preferences: ^2.0.18
  audioplayers: ^3.0.1
  firebase_core: ^2.7.0
  firebase_database: ^10.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0
  build_runner:
  flutter_gen_runner:

flutter_gen:
  output: .dart_tool/flutter_gen/gen/

flutter_icons:
  android: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "assets/images/icon_adaptive_background.png"
  adaptive_icon_foreground: "assets/images/icon_adaptive_foreground.png"
  min_sdk_android: 19
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#262D47"
    theme_color: "#262D47"

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section.
  assets:
    # Lesson contents
    - lessons/en/
    - lessons/de/

    # Rive animations
    - assets/animations/quantos_logo_intro.riv
    - assets/animations/quantos_logo_idle.riv
    - assets/animations/circular_progress_indicator.riv

    - assets/animations/age_selection.riv
    - assets/animations/experience_selection.riv

    # Lection header and icon animations
    - assets/animations/lections/
    
    # App images
    - assets/images/logo.png
    - assets/images/background.png
    - assets/images/background_desktop.png
    - assets/images/icon_background.png
    - assets/images/icon_background_gradient.png
    - assets/images/profile_background.png
    - assets/images/profile_foreground.png

    # Lection content images
    - assets/images/lessons/

    # Sound effects
    - assets/sounds/

    # Credentials
    - lib/credentials.json


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section.
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
    - family: Josefin Sans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
        - asset: assets/fonts/JosefinSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/JosefinSans-Bold.ttf
          weight: 700