// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA09Syt7gls-VuHuNzhsihaXqXzXV7luzw',
    appId: '1:986404112021:web:ed97a606923142ce6dfd9c',
    messagingSenderId: '986404112021',
    projectId: 'quantos-learning-app',
    authDomain: 'quantos-learning-app.firebaseapp.com',
    databaseURL: 'https://quantos-learning-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quantos-learning-app.appspot.com',
    measurementId: 'G-129XBJ4WT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCsPqscLxN3SUxfLR4caZf2P_Az42fozM',
    appId: '1:986404112021:android:64b814f34c09faaa6dfd9c',
    messagingSenderId: '986404112021',
    projectId: 'quantos-learning-app',
    databaseURL: 'https://quantos-learning-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quantos-learning-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC64girE8JAQhTapGvPEBtt6bzv9eGcXdQ',
    appId: '1:986404112021:ios:48dfb3be34056e436dfd9c',
    messagingSenderId: '986404112021',
    projectId: 'quantos-learning-app',
    databaseURL: 'https://quantos-learning-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'quantos-learning-app.appspot.com',
    iosClientId: '986404112021-po2efaenmg9d4gvkaklc92gjlj8abrj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.quantos',
  );
}
